name: Dockerized MERN CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Optional: Build Docker locally (not required for EC2 deploy)
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: (Optional) Build Docker Containers locally
      run: docker-compose build

    - name: (Optional) Run Containers locally
      run: docker-compose up -d

    # 3️⃣ Deploy to EC2
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          if [ ! -d "MinorProject" ]; then
            git clone https://github.com/Aman-agraw-35/MinorProject.git MinorProject
          fi
          cd MinorProject
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
